### ISSUE TITLE
Lack of plugins support with pylint

### ISSUE THREAD

**Issue by Passeriform** [elarivie/atom-python-linters#1]
# ⓘ Summary
While developing for a framework (Django, Flask, etc.) there exist plugins for resolving pylint issues with lack of framework context. Pylint at it's core supports option of including plugins (--load-plugins) to resolve this issue. Generally plugins can be loaded in configuration files (.pylintrc or setup.cfg) but some crucial plugins require them loaded through the command line itself. Thus making it impossible to load them using the utility.

# 👣 Reproduction steps

1. Create boilerplate Django application.
`django-admin startapp <application>`
2. Define a Django `model` in `models.py`.
3. Import `model` in `views.py` and use its objects.
`<model>.objects.all()`
2. Install `pylint-django` using pip.
`pip install pylint-django`
3. Define `setup.cfg` with `load_plugins=pylint-django`.
4. Use pylint from the utility to lint the files

# 🦄 Expected behaviour:

The linter shouldn't return any errors when run on the file.

# 🐞 Actual behaviour:

Linter returns:
`E1101: Class '<model>' has no 'objects' member (no-member)`

# 📖 Stack trace:

Not a stack trace issue

## 💬 Comment:

The issue pops up on flask using SQLAlchemy.

PS: Love the utility. Thanks for the effort. 😊

### Update:
> 3. Define `setup.cfg` with `load_plugins=pylint-django`.
in [reproduction steps](#-reproduction-steps) is mistyped.

Corrected to:
> 3. Define `setup.cfg` with `load-plugins=pylint_django`.

**Comment by elarivie** [comment]
Hello @Passeriform,

Thanks for your issue report and comments, it is always nice to know that people are using and appreciate developed tools.
  
In the issue you wrote:

> but some crucial plugins require them loaded through the command line itself. Thus making it impossible to load them using the utility.

🙂 Nothing is impossible

You can adapt the following script to your need to wrap python call and adjust whatever is needed to the environment and/or to the command line parameters:
[python_wrapper.sh.txt](https://github.com/elarivie/atom-python-linters/files/4073302/python_wrapper.sh.txt)

Let me know if it solves your issue.

**Note:** If it solves your issue... could you send me back the modified version... I'll check it and see if modification could be done to python-linters to better support that use-case.

**Note:** I also want to keep the packages simple without tons of settings... so in the end maybe the wrapper may be a good enough solution.

**Comment by Passeriform** [comment]
> You can adapt the following script to your need to wrap python call and adjust whatever is needed to the environment and/or to the command line parameters:
> [python_wrapper.sh.txt](https://github.com/elarivie/atom-python-linters/files/4073302/python_wrapper.sh.txt)

Ahhh clever solution. I'll try it when I get to my system.

My first response to the problem was maybe having advanced settings for having the functionality yet keeping it visually minimal. I generally would rather have a configuration file setup than a rerouted python.

> **Note:** I also want to keep the packages simple without tons of settings... so in the end maybe the wrapper may be a good enough solution.

But again, I also get your sentiment here.

If it aligns with the project's motive, I might like to contribute to it.

Thanks again.

**Comment by elarivie** [comment]
@Passeriform 

I am open for [contribution](https://github.com/elarivie/atom-python-linters/blob/master/CONTRIBUTING.md).

If you want to contribute I'll be glad to accept a pull request.

In the meantime I have read a little about the '--load-plugins' parameter of pylint.

While browsing the web I saw a setup.cfg which contained:

    [pylint]
    load-plugins=pylint_common, pylint_django, pylint_plugin_utils

And another one which contained:

    [pylint]
    load-plugins=

While from your first message:

> 5. Define setup.cfg with load_plugins=pylint-django

You seem to have two typo, both about (minus) vs (underscore)

load-plugins=  
load_plugins=

**and**

pylint-django  
pylint_django

If we trust the web:
1. It is possible to load the plugin of django from setup.cfg
2. The good syntax is:

        load-plugins=pylint_django

@Passeriform: **Can you confirm that your issue is not due to a double typo in your setup.cfg**

**Comment by Passeriform** [comment]
@elarivie 

> You seem to have two typo, both about (minus) vs (underscore)
> 
> load-plugins=
> load_plugins=
> 
> **and**
> 
> pylint-django
> pylint_django
> 
> If we trust the web:
> 
>     1. It is possible to load the plugin of django from setup.cfg
> 
>     2. The good syntax is:
>        ```
>         load-plugins=pylint_django
>        ```
> 
> 
> @Passeriform: **Can you confirm that your issue is not due to a double typo in your setup.cfg**



I tried the setup.cfg with the following options:

`load_plugins=pylint_django`
`load_plugins=pylint-django`
`load-plugins=pylint_django`
`load-plugins=pylint-django`

None of these work.

There was definitely a typo in the question as I had modified the setup.cfg try these options out on command line and forgot to reset them back before posting the issue.

The weird part about this is that `pylint_common` gets loaded perfectly using load_plugins (which is what I'm using in my original `setup.cfg`). Yet there are some plugins that fail to load through `setup.cfg`



> I am open for [contribution](https://github.com/elarivie/atom-python-linters/blob/master/CONTRIBUTING.md).
> 
> If you want to contribute I'll be glad to accept a pull request.


Thanks, I'll create a PR right away.

**Comment by elarivie** [comment]
@Passeriform 

After few trial and error I found a solution…
In the configuration file 'setup.cfg' put the 'load-plugins' setting under a section called [MASTER]

        [MASTER]
        load-plugins=pylint_django

You can still have a pylint section with other settings like for example disable:

        [pylint]
        disable=C0114

For some reason (clearly a bug in pylint) the 'load-plugins' setting MUST be in a section called 'MASTER' else it is ignored

while the other settings like 'disable' works fine under the section [pylint] and under the section [MASTER]

**Note for futur reference**
Those are the python module I had to install:

* python3 -m pip install django
* python3 -m pip install pylint-django

This is a simple python/django file to reproduce the issue:

    from django.db import models
    class Person(models.Model):
        first_name = models.CharField(max_length=30)
    Person.objects.all()


**Note for futur reference:**
To easily make sure the module is being loaded ... misstype the module name, pylint will throw an error when linting, if it doesn't the module is not even attempted to be loaded

`"pylintTraceback (most recent call last):\n File \"/usr/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n \"main\", mod_spec)\n File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n exec(code, run_globals)\n File \"/home/administrateur/.local/lib/python3.7/site-packages/pylint/main.py\", line 7, in \n pylint.run_pylint()\n File \"/home/administrateur/.local/lib/python3.7/site-packages/pylint/init.py\", line 23, in run_pylint\n PylintRun(sys.argv[1:])\n File \"/home/administrateur/.local/lib/python3.7/site-packages/pylint/lint.py\", line 1686, in init\n linter.load_plugin_modules(plugins)\n File \"/home/administrateur/.local/lib/python3.7/site-packages/pylint/lint.py\", line 660, in load_plugin_modules\n module = modutils.load_module_from_name(modname)\n File \"/home/administrateur/.local/lib/python3.7/site-packages/astroid/modutils.py\", line 198, in load_module_from_name\n return load_module_from_modpath(dotted_name.split(\".\"), path, use_sys)\n File \"/home/administrateur/.local/lib/python3.7/site-packages/astroid/modutils.py\", line 240, in load_module_from_modpath\n mp_file, mp_filename, mp_desc = imp.find_module(part, path)\n File \"/usr/lib/python3.7/imp.py\", line 296, in find_module\n raise ImportError(_ERR_MSG.format(name), name=name)\nImportError: No module named 'pylint_djangoXXX'"`

**Comment by Passeriform** [comment]
Wow. Thanks for the debug @elarivie.
Made the suggested changes. It works flawlessly.

I'll report the issue at Pylint and refer in this issue.

P.S.

**Comment by elarivie** [comment]
@Passeriform, your welcome.

But I want to retract the part where I said it is a bug in pylint.

I did look at pylint source code and it is hard coded pretty early in the flow to look at ["MASTER"] ⇒ "load-plugins"
https://github.com/PyCQA/pylint/blob/master/pylint/lint.py#L1724

so this part is good, it was never written anywhere that the setting has to be under a section named [pylint].

The only remaining strange part is that the 'disable' settings works when defined in the section [MASTER] and in the section [pylint], in fact I tried and it even works if defined under any section name, even:

        [XXX]
        disable=C0114

even:

        [mypy]
        disable=C0114

So pylint is really not picky about section names for its settings.

Nowhere in the pylint code I saw that the config should have a section named [pylint].

I don't know where this 'pseudo convention' came from (probably derived from flake8, mypy, pydocstyle... which  each require a sections name of their name else they don't even run) but it didn't come from the project pylint.

But since pylint blindly loads settings from any section name nobody noticed that the [pylint] section is a common practice but not a requirement

This surely may create future issue if a tool has matching name for its settings, but for now it works :)
