### ISSUE TITLE
Cannot parse file at the beginning

### ISSUE THREAD

**Issue by OgnjenMilicevic** [elarivie/atom-python-linters#7]
Every python file I have has the same non-informative error:

https://ibb.co/mt9dB1j

This error disappears when I turn off Pylint.

Is this a bug?

**Comment by elarivie** [comment]
Hello @OgnjenMilicevic 

This is not a bug.

Pylint has effectively failed to parse the file with one of the two following error message
* 'Parsing Python code failed'
* * https://github.com/elarivie/atom-python-linters/blob/54190a2817ada801849bee4cffca95bd75123573/lib/lint.js#L785
* 'AttributeError: \'list\' object has no attribute \'args\''
* * https://github.com/elarivie/atom-python-linters/blob/54190a2817ada801849bee4cffca95bd75123573/lib/lint.js#L795

Those two scenarios are detected by python-linters and a lint error is reported at the beginning of the file since no line information is provided by Pylint.

I can help to debug your python file but I would need it.

If possible could you send me one of your problematic python file, if you don't want to send it in public directly within this github issue, you can send it to me by email ericlariviere@hotmail.com

**Comment by OgnjenMilicevic** [comment]
Thank you, you are very kind (in addition to being responsive). I will send you the whole file, as it happens to literaly all of my files:

```
#!/usr/bin/env python3

"""JSON-like manipulations for convenience."""

import sys
import json


def tsv2json(fname, sep):
    """Convert tsv to python dict (misnomer 2json)."""
    with open(fname, 'r') as fin:
        header = fin.readline().rstrip().split(sep)
        keys = [x for x in header]
        json_dict = {k: [] for k in keys}
        for line in fin:
            parts = line.rstrip().split(sep)
            for i in range(len(parts)):
                json_dict[keys[i]].append(parts[i])
    return json_dict


if __name__ == "main":
    # python convert.py tsv2json input_file sep
    fun = sys.argv[1]
    fin_name = sys.argv[2]
    sep = sys.argv[3]
    pipeline = "FastQCsToUnmappedBamWf"
    json_dict = tsv2json(fin_name, sep)
    print(json_dict)
    # Write inputs for W1
    with open("inputsW7.json", "w") as out_json:
        json.dump(json_dict, out_json, indent=0)

```

**Comment by elarivie** [comment]
I copy pasted your code and it lint well without parsing error:
![image](https://user-images.githubusercontent.com/8286066/98952293-4afc3080-24c9-11eb-9422-e9d21d680a0b.png)

So the problem is somewhere else

You say that it occurs on every file... Do you have a config file (setup.cfg)? (can you attach to this issue its content)

To investigate the issue, let's first try to replicate within the CLI:

Run the following commands if you have a setup.cfg file:
```shell
cd <THE DIRECTORY CONTAINING THE setup.cfg>;
cat <FULL PATH TO A PYTHON FILE TO LINT> | python3 -m pylint --rcfile <THE FULL PATH TO setup.cfg> --score n --output-format text --from-stdin <FULL PATH TO A PYTHON FILE TO LINT>;
```

Run the following commands if you **don't** have a setup.cfg file:
```shell
cat <FULL PATH TO A PYTHON FILE TO LINT> | python3 -m pylint --score n --output-format text --from-stdin <FULL PATH TO A PYTHON FILE TO LINT>;
```


The above shell commands replicate what python-linters internally do when calling pylint.
Don't forget to correctly adjust all the variables surrounded by <>

Let me know what you get as output when running the above commands

**Comment by OgnjenMilicevic** [comment]
I don't have setup.cfg, so I ran the command you gave:

```
(base) ognjenmilicevic@Ognjens-13:~$ cat "/Users/ognjenmilicevic/Pacific/PA_Tools/Docker/Scripts/run_multiWDL.py" | python -m pylint --score n --output-format text --from-stdin "/Users/ognjenmilicevic/Pacific/PA_Tools/Docker/Scripts/run_multiWDL.py";
Usage:  __main__.py [options] modules_or_packages

  Check that module(s) satisfy a coding standard (and more !).

    __main__.py --help

  Display this help message and exit.

    __main__.py --help-msg <msg-id>[,<msg-id>]

  Display help messages about given message identifiers and exit.
```

The only online reference of such a message is [this](https://github.com/microsoft/vscode-python/issues/10539).
My pylint version is:

```
pylint --version
pylint 2.3.1
astroid 2.2.5
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by elarivie** [comment]
Hello @OgnjenMilicevic,

Good news with the information you provided I have been able to reproduce your situation.

You currently have pylint 2.3.1…

With pylint 2.3.1 I get the same parsing error.

**Note:** the current latest pylint version is 2.6.0
With pylint 2.6.0 everything works fine

You should update pylint to latest version by running:
```shell
python3 -m pip install -U pylint
```
Note: The parameter -U means update

**Extra info:**

You can uninstall pylint with
```shell
python3 -m pip uninstall pylint
```

And then install whichever specific version that you want with:
python3 -m pip install 'pylint==2.3.1'
or 
python3 -m pip install 'pylint==2.6.0'


For the atom package python-linters, I don't plan to support other version than the latest version of the lint tools

You should therefore sometimes run: 
```shell
python3 -m pip install -U pylint mypy pydocstyle flake8
```

Let me know if it fixes your issue.

**Comment by OgnjenMilicevic** [comment]
You are right, this solves it. A million thanks!
