### ISSUE TITLE
setup.cfg not working

### ISSUE THREAD

**Issue by euphoniumlover** [elarivie/atom-python-linters#8]
# ⓘ Summary

I've tried to setup a `setup.cfg` for pylint and it's not doing anything.

# 👣 Reproduction steps

1. Default value for Configuration File Path `%PROJECTPATH/setup.cfg`
2. Use a setup.cfg in root of your project containing exactly this:
```
#[pylint]
#disable = D107,R0913

#[flake8]
#max-line-length = 82
```
I also tried using `#[pylint:pydocstyle]` or 
```
#[pylint]
#[pydocstyle]
```
but none of those work.

# 🦄 Expected behaviour:

For the error codes listed to be disabled like normal, and the expected line length to be adjusted.

# 🐞 Actual behaviour:

The errors are still listed.

## 📷 Screenshot:

![image](https://user-images.githubusercontent.com/40502986/100160858-39217280-2e65-11eb-9999-050b54a04e42.png)
![image](https://user-images.githubusercontent.com/40502986/100160960-6837e400-2e65-11eb-81ae-692d1e937cad.png)

## 💬 Comment:

Thank you so much for your work every other atom linter was crashing and getting tons of error messages and are unmaintained. I was almost doubting atom's ability until I saw this. I can deal with it for now but if you could fix this (or tell me what stupid mistake I made) that would be great as google hasn't been helpful with solving this problem. 

Thanks!

**Comment by elarivie** [comment]
Hello @Th3OneAndOnly 

Effectively writing the setup.cfg file can be tricky since there is barely no documentation about it within the different lint tools.  And some of them have a very strange expectation/behavior about its content (FYI see #1) for a good example of unexpected syntax

Here is a setup.cfg file which I am using in one of my project:

[setup.cfg](https://github.com/elarivie/atom-python-linters/files/5593745/setup.cfg.txt)

you can use and adapt it to your need.

You probably do not need all the settings that it contains but it will provide you a very good start to get you up to speed.

Let me know if it solves the issue that you have

**Comment by euphoniumlover** [comment]
Thank you. I did not know that the #'s weren't needed, since any existing documentation uses them for some reason.
